platform = "android"

[[distribution]]
name = "pyone32"
version = "1.0.0"
origin = "direct"
entry_point = "pyone32._native"

[[distribution]]
name = "pytwo32"
version = "1.0.0"
origin = "direct"
entry_point = "pytwo32._native"
