platform = "android"

[[distribution]]
name = "pyauth"
version = "2.0.0"
origin = "direct"
entry_point = "pyauth._native"

[[distribution]]
name = "pyscope"
version = "1.0.0"
origin = "direct"
entry_point = "pyscope._native"
