platform = "ios"

[[distribution]]
name = "examplytics"
version = "1.0.0"
origin = "direct"
entry_point = "examplytics._native"

[[distribution]]
name = "pyunrelated"
version = "1.0.0"
origin = "not-in-closure"
entry_point = "pyunrelated._native"
