platform = "ios"

[[distribution]]
name = "pyalpha"
version = "1.0.0"
origin = "direct"
entry_point = "pyalpha._native"

[[distribution]]
name = "pybeta"
version = "1.0.0"
origin = "direct"
entry_point = "pybeta._native"
