platform = "ios"

[[distribution]]
name = "pyone35"
version = "1.0.0"
origin = "direct"
entry_point = "pyone35._native"

[[distribution]]
name = "pytwo35"
version = "1.0.0"
origin = "direct"
entry_point = "pytwo35._native"
